feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

service:
  url: http://154.53.58.243:3030/api
  login:
    name: login-service
  menu:
    name: menu-service
  rol:
    name: rol-service
  user:
    name: user-service
  table:
    name: table-service
  bill:
    name: bill-service
  category:
    name: category-service
  provider:
    name: provider-service
  email:
    name: email-service
  ingredient:
    name: ingredient-service
  recipe:
    name: recipe-service
  image:
    name: image-service
    validations:
      min_pixels: El tamaño de la imagen debe ser mayor a 500x500




server:
  port: 8080
  servlet:
    context-path: /api-sr

spring:
  application:
    name: Rest Consumer

