feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

service:
  url: http://154.53.58.243:3030/api/v1
  login:
    name: login-service
  menu:
    name: menu-service
  rol:
    name: rol-service
  user:
    name: user-service
  table:
    name: table-service

server:
  port: 8080
  servlet:
    context-path: /api-sr

spring:
  application:
    name: Rest Consumer

